name: Terraform Infrastructure Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0  # Specify your Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Initialize Terraform
        working-directory: terrform-infra-code/
        run: terraform init

      # - name: Plan Terraform
      #   working-directory: terrform-infra-code/
      #   run: terraform plan

      # - name: Apply Terraform
      #   working-directory: terrform-infra-code/
      #   run: terraform apply -auto-approve

      - name: Destroy Terraform Infrastructure
        working-directory: terrform-infra-code/
        run: terraform destroy -auto-approve